package com.sup2i.food.payment.exception;

public enum PaymentErrorCode {
    ORDER_NOT_FOUND,
    INVALID_ORDER_STATUS,
    ORDER_EXPIRED,
    PAYMENT_ALREADY_COMPLETED,
    PAYMENT_AMOUNT_MISMATCH,
    PAYMENT_FAILED,
    IDEMPOTENCY_CONFLICT,
    CONCURRENT_MODIFICATION,
    POS_SESSION_NOT_OPEN
}