package com.sup2i.food.canteen.exception;

public enum CanteenErrorCode {
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    IDEMPOTENCY_CONFLICT,
    CANTEEN_RESERVATION_CLOSED,
    CANTEEN_ALREADY_RESERVED,
    INVALID_QR,
    FOOD_PASS_BLOCKED,
    FOOD_PASS_LOST,
    FOOD_PASS_REVOKED,
    FOOD_PASS_EXPIRED,
    STUDENT_INACTIVE,
    SUBSCRIPTION_INACTIVE,
    ENTITLEMENT_EXPIRED,
    MEAL_NOT_ALLOWED,
    QUOTA_EXHAUSTED,
    DAILY_LIMIT_REACHED,
    MEAL_ALREADY_USED
}
